homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

story4/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('homepage.urls')),
    path('', include('storyaan.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
]

story5/urls.py
from . import views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from .views import matakuliah

app_name = 'story5'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:matkul_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('delete/<int:matkul_id>', views.delete, name='delete'),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='kegiatan'),
]

storyaan/urls.py
from django.urls import path
from . import views

app_name = 'storyaan'

urlpatterns = [
    path('', views.home, name='andreaan'),
    path('data/', views.profile, name='aan2'),
    path('comingsoon/', views.coming, name='comingsoon'),
]

homepage/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

class MataKuliah(models.Model):
    nama_matkul = models.CharField(max_length=250)
    dosen = models.CharField(max_length=500)
    jumlah_sks = models.PositiveIntegerField(default=3)
    deskripsi = models.CharField(max_length=1000)
    tahun_semester = models.CharField(max_length=250)
    ruang_kelas = models.CharField(max_length=300)

    def __str__(self):
        return self.nama_matkul

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama = models.CharField(max_length=64)
    def __str__(self):
        return self.nama

class Pesertanya(models.Model):
    nama = models.CharField(max_length=64)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.nama

storyaan/models.py
from django.db import models

# Create your models here.

story5/forms.py
from django import forms
from .models import *

class MataKuliahForm(forms.ModelForm):

    class Meta:
        model = MataKuliah
        fields = '__all__'

story6/forms.py
from django import forms

class KegiatanForm(forms.Form):
    nama_kegiatan = forms.CharField(label='Nama Kegiatan', max_length=64,widget=forms.TextInput(attrs={'class':'form-control'}))

class PesertaForm(forms.Form):
    nama_peserta = forms.CharField(label='Nama Peserta', max_length=64, widget=forms.TextInput(attrs={'class':'form-control'}))

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

story5/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import MataKuliah
from .forms import *
from django.contrib import messages
from django.contrib.messages import constants

def index(request):
    all_matkul = MataKuliah.objects.all()
    return render(request, 'matakuliah.html', {'all_matkul': all_matkul})

def detail(request, matkul_id):
    matkul = get_object_or_404(MataKuliah, pk=matkul_id)
    return render(request, 'detail.html', {'matkul': matkul})

def add(request):
    if request.method == "POST":
        form = MataKuliahForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, (f"Mata kuliah {request.POST['nama_matkul']} berhasil ditambahkan!"))
            redirect('/')
        else:
            messages.warning(request, ("Data yang anda masukkan tidak sesuai kriteria."))
            redirect('/')
    return render(request, 'add.html')

def delete(request, matkul_id):
    matkul = MataKuliah.objects.get(id=matkul_id)
    matkul.delete()
    messages.success(request, (f"Mata Kuliah {matkul} berhasil dihapus"))
    return redirect('story5:index')

story6/views.py
from django.shortcuts import render
from . import forms
from . import models
from django.http import HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@csrf_exempt
def index(request):
    if request.method == 'POST':
        if 'nama_kegiatan' in request.POST:
            formkegiatan = forms.KegiatanForm(request.POST)
            if formkegiatan.is_valid():
                data = formkegiatan.cleaned_data
                data_input = models.Kegiatan()
                data_input.nama = data['nama_kegiatan']
                data_input.save()
        elif 'nama_peserta' in request.POST and 'id_kegiatan' in request.POST:
            formpeserta = forms.PesertaForm(request.POST)
            if formpeserta.is_valid():
                try:
                    kegiatan = models.Kegiatan.objects.get(id=request.POST['id_kegiatan'])                
                    data = formpeserta.cleaned_data
                    data_input = models.Pesertanya()
                    data_input.nama = data['nama_peserta']
                    data_input.kegiatan = kegiatan
                    data_input.save()
                except :
                    return HttpResponseBadRequest("Bad Request")
        elif 'delete-peserta' in request.POST:
            try:
                models.Pesertanya.objects.get(id=request.POST['delete-peserta']).delete()
            except:
                return HttpResponseBadRequest("Bad Request")
    list_kegiatan = models.Kegiatan.objects.all()
    data_kegiatan_lengkap = []
    for kegiatan in list_kegiatan:
        list_peserta = models.Pesertanya.objects.filter(kegiatan = kegiatan)
        data_peserta =[]
        for peserta in list_peserta:
            data_peserta.append(peserta)
        data_kegiatan_lengkap.append((kegiatan,data_peserta))
    return render(request, 'kegiatan.html', {'formkegiatan':forms.KegiatanForm, 'formpeserta':forms.PesertaForm, 'data_kegiatan':data_kegiatan_lengkap})

storyaan/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'andreaan.html')

def profile(request):
    return render(request, 'aan2.html')

def coming(request):
    return render(request, 'comingsoon.html')

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>
                Story 1 : Profil Andreas Ilham
        </title>

        <center><h2 style="color: cadetblue;">Halloo guuyysss</h2></center>
        <center><h2 style="color: cadetblue;">Welcome to my websiteeee :)</h2></center>

        <div id="foto profil">
            <center><img src="{% static 'Foto.png' %}"style="width: auto; height: auto; max-width: 50%;"</center>
            
        </div>

   </head>


    <body>
        <style>
            body{
                background-color:bisque
            }
            img {
                image-orientation: from-image;
            }
        </style>
    
    <div id="Biodata">
        <center><h2>Ini beberapa informasi tentang aku yaa :D</h2></center>
        <h4>Nama : Andreas Ilham</h2>
        <h4>NPM : 1906399543</h2>
        <h4>Angkatan: Maung 2019</h2>
        <h4>Tempat Kuliah : Universitas Indonesia</h2>
        <h4>Hobi : Membaca, Menyanyi, dan Makan</h2>
    </div>
    
    <div id="Deskripsi Diri">
        <h2>Deskripsi Diri</h2>
        <p>Saya adalah seseorang yang sangat suka bersosialisasi, serta suka public speaking. Berbicara di hadapan orang banyak melatih saya untuk bisa berani tampil. Sekarang saya merupakan mahasiswa jurusan Sistem Informasi di Universitas Indonesia.</p>
    </div>



    <div id="Riwayat Pendidikan">
        <center><h2>Riwayat Pendidikan</h2></center>
        <center><table class="Pendidikan"></center>
            <style>
                table.Pendidikan td, tr {
                    border: 1px solid brown;}
                table.Pendidikan {
                    border-collapse: collapse;}
                table.Pendidikan {
                    padding: 8px;}
            </style>

            <tr align="center">
                <td><strong>Pendidikan</strong></td>
                <td><strong>Tahun</strong></td>
            </tr>

            <tr>
                <td align="center">TK Islan Al-Falah Kota Bukittinggi</td>
                <td align="center">2005 - 2006</td>
            </tr>

            <tr>
                <td align="center">SD Negeri 04 Biaro</td>
                <td align="center">2006 - 2012</td>
            </tr>

            <tr>
                <td align="center">SMP Negeri 1 IV Angkek</td>
                <td align="center">2012 - 2015</td>
            </tr>

            <tr>
                <td align="center">SMA Negeri 1 Bukittinggi</td>
                <td align="center">2015 - 2018</td>
            </tr>

            <tr>
                <td align="center"> Fakultas Ilmu Komputer Universitas Indonesia </td>
                <td align="center">2019 - Sekarang</td>
            </tr>

        </table>
    </div>
   
    <div id="Social Media">
        <center><h2>Find me at :</h2></center>
            <center><a href="http://instagram.com/andreas_ilham" target="_blank">
                <img src="{% static 'Instagram.png' %}"
            width="50" height="50">
            </a></center>

            <center><a href="http://line.me/ti/p/aan.cute" target="_blank">
                <img src="{% static 'Line.png' %}"
            width="50" height="50">
            </a></center>

            <center><a href="https://www.linkedin.com/in/andreas-ilham-65a358194" target="_blank">
                <img src="{% static 'Linkedin.png' %}"
            width="50" height="50">
             </a></center>
    </div>
</body>
</html>

story5/templates/add.html
{% extends 'navbar.html' %}
{% block content %}

<div class="container">
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
	{% endfor %}
  {% endif %}
    <form class="mt-5" method="POST">
      {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-5">
            <label>Nama Mata Kuliah</label>
            <input type="text" class="form-control" id="nama_matkul" name="nama_matkul" required>          
          </div>
          <div class="form-group col-md-5">
            <label for="dosen">Dosen Pengajar</label>
            <input type="text" class="form-control" id="dosen" name="dosen" required>          
          </div>
					<div class="form-group col-md-2">
            <label for="sks">Jumlah SKS</label>
            <input type="number" class="form-control" id="jumlah_sks" name="jumlah_sks" required>          
          </div>
        </div>
				<div class="form-row">
          <div class="form-group col-md-5">
            <label for="tahunAjar">Semester (ex: Gasal 2019/2020) </label>
            <input type="text" class="form-control" id="tahun_semester" name="tahun_semester" required>
          </div>
          <div class="form-group col-md-2">
            <label for="ruang">Ruang</label>
            <input type="text" class="form-control" id="ruang_kelas" name="ruang_kelas" required>
          </div>
        </div>
				<div class="form-group">
					<label for="deskripsi">Deskripsi</label>
					<textarea class="form-control" id="deskripsi" rows="3" name="deskripsi" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
      </form>
</div>
{% endblock content %}

story5/templates/detail.html
{% extends 'navbar.html' %}
{% block content %}


<div class="container my-4">
    <div class="jumbotron">
        <h1 class="display-4">{{ matkul.nama_matkul }}</h1>
        <p class="lead">{{ matkul.tahun_semester }}</p>
        <p>{{ matkul.deskripsi }}</p>
        <hr class="my-4">
        <div class="row">
            <h4 class="col-10 col-md-3">Ruang : <span class="badge badge-dark">{{ matkul.ruang_kelas }}</span></h4>
            <h4 class="col-10 col-md-3">Dosen : <span class="badge badge-dark">{{ matkul.dosen }}</span></h4>
            <h4 class="col-10 col-md-3">Jumlah SKS : <span class="badge badge-dark">{{ matkul.jumlah_sks }} SKS</span></h4>
        </div>
        <a class="btn btn-outline-dark mt-4" href="{% url 'story5:index' %}" role="button">BACK</a>
    </div>
</div>
{% endblock content %}

story5/templates/matakuliah.html
{% extends 'navbar.html' %}
{% block content %}


<div class="container my-4">
    <a class="nav-link" href="{%url 'story5:add' %}">Add Jadwal<span class="sr-only">(current)</span></a>
  {% if messages %}
	{% for message in messages %}
		<div class="alert alert-warning alert-dismissible fade show mt-4" role="alert">
			{{ message }}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	{% endfor %}
    {% endif %}
    
  {%if all_matkul%}
        {% for matkul in all_matkul %}
        <div class="card mt-3">
                <div class="card-body d-flex justify-content-between flex-column flex-md-row">
                    <div>
                        <a href="{% url 'story5:detail' matkul.id %}"><h5 class="card-title">{{ matkul.nama_matkul }}</h5></a>
                        <h6 class="card-subtitle mb-2 text-muted">{{ matkul.tahun_semester}}</h6>
                    </div>
                    <a href="{% url 'story5:delete' matkul.id %}" class="card-link text-danger mt-3 mt-md-0 mr-md-4 align-self-center">DELETE</a>
                </div>
        </div>
        {%endfor%}

    {%else%}
     <h3>You don't have any matkul.</h3>
{%endif%}
</div>
{% endblock content %}

story5/templates/navbar.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSS-->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sh384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">


    <title>Story 5 Aan Keren</title>
</head>

<body id="body">
    <nav id="navbar" class="navbar fixed-top navbar navbar-expand-lg navbar-light " style="background-color:#3fa2ab">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
        <div id="collapse" class="collapse navbar-collapse" style="justify-content: flex-end;" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'storyaan:andreaan' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#education">Education</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#experience">Experience</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#traits">Traits</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#skills">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#sosmed">Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story5:index' %}#jadwal">Jadwal</a>
                </li>
            </ul>
        </div>
    </nav>
{% block content %} {% endblock %}

</body>

</html>

story6/templates/kegiatan.html
{% extends 'navbar.html' %}

{% block content %}
<div class="container mt-6">
    <div class="card text-center bg-info mb-3 justify-self-center">
        <div class="card-header">
          <h3>Tambahkan Kegiatan Baru </h3>
        </div>
        <form action="" method="post" class="mt-4 kegiatan-form" class="card-text">
            {{formkegiatan}}
            {% csrf_token %}
            <input type="submit" class="btn btn-danger mt-2" value="Tambahkan"> 
        </form>
        <form action="" class="d-none" method="post" id="deletePesertaForm">
            {% csrf_token %}
            <input type="hidden" name="delete-peserta" value="" id="deletePeserta">
        </form>
      </div>

    <div class="container-kegiatan" style="align-content: center;">
        {% for kegiatan in data_kegiatan %}
        <div class="card card-kegiatan bg-warning mb-3 text-center">
            <div class="card-body">
                <h5 class="card-title"><b>{{kegiatan.0.nama}} </b></h5>
                <p class="card-text">
                    Peserta :  <span class="badge badge-pill">{{kegiatan.1|length}}</span><br>
                    <div class="list-peserta-container">
                        {% for peserta in kegiatan.1 %}
                        <div class="list-peserta-item">
                            {{peserta.nama}}
                            <button type="button" onclick="deletePeserta({{peserta.id}})" class="close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endfor %}      
                    </div>
                </p>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal" onclick="tambahPeserta('{{kegiatan.0.nama}}',{{kegiatan.0.id}})">Tambahkan Peserta</button>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content ">
            <div class="modal-header ">
              <h5 class="modal-title" id="exampleModalLabel">Tambahkan Peserta</h5>
              <button type="button"class="btn btn-info" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                Nama Kegiatan : <span id="namaKegiatan"></span>
              <form action="" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="id_kegiatan" id="idKegiatan" value="">
                {{formpeserta}}
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Daftar</button>
            </div>
            </form>
          </div>
        </div>
      </div>
</div>
<script>
function tambahPeserta(namaKegiatan, idKegiatan){
    document.getElementById('namaKegiatan').innerHTML=namaKegiatan;
    document.getElementById('idKegiatan').value=idKegiatan;
}

function deletePeserta(pesertaid){
    document.getElementById('deletePeserta').value = pesertaid;
    document.getElementById('deletePesertaForm').submit();
}
</script>
{% endblock %}

storyaan/templates/andreaan.html
{% extends 'base.html'%} {% load static %} {% block content %}
    <section id="background">
      <div>
        <h2 id="atas">
          <marquee behavior="scroll" direction="left" scrollamount="30">Welcome to my Personal Website :D</marquee>
        </h2>
      </div>
        <div class="row">
            <div class="col-lg-6">
                <img id="img" src="{% static 'Foto.png' %}">
            </div>
            <div class="col-lg-6" id="Deskripsi">
                <h2 id="desk">Deskripsi Diri</h2>
                <p id="isi">Saya merupakan mahasiswa jurusan Sistem Informasi Fakultas Ilmu Komputer Universitas Indonesia. Banyak yang bilang saya orang yang pemalu serta pendiam. Saya mempunyai motto hidup yaitu “If You Think You Can, You Can”. Saya adalah orang yang sangat suka bersosialisasi walaupun pendiam.</p>
            </div>
        </div>
    </section>
    <section>
        <div id="button" >
            <a href="{% url 'storyaan:comingsoon' %}" class="btn btn-primary" >Coming Soon>></a>
        </div>
    </section>
    {% endblock %}

storyaan/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSS-->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">


    <title>Story 3 Aan Keren</title>
</head>

<body id="body">
    <nav id="navbar" class="navbar fixed-top navbar navbar-expand-lg navbar-light " style="background-color:#3fa2ab">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
        <div id="collapse" class="collapse navbar-collapse" style="justify-content: flex-end;" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'storyaan:andreaan' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#education">Education</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#experience">Experience</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#traits">Traits</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#skills">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'storyaan:aan2' %}#sosmed">Contacts</a>
                </li>
            </ul>
        </div>
    </nav>
{% block content %} {% endblock %}

</body>

</html>

storyaan/templates/comingsoon.html
{% extends 'base.html'%} {% load static %} {% block content %}
    <dd class="col-lg-9">
        <h1 id="atas">Something New <br>is about to Come.</h1>
        <br>
        <h2 id="atas">------Coming Soon!</h2>
    </dd>
    {% endblock %}